### PR TITLE
added ro import

### PR DESCRIPTION
**Pull request by marieALaporte**
@cmungall I don’t know why the -r does not keep the ro labels of all
the imported properties. Maybe that is not the proper way to do that. 
I don’t know how to ‘cleanly’ import the import file in the
plant-ontology.obo

### CODE REVIEW

**Comment by cmungall** [comment]
OK, deep into obo-owl weirdness here. What you need to do is run another command `--add-obo-shorthand-to-properties`

**Comment by marieALaporte** [comment]
@cmungall Before to accept this PR, what's the proper way to (1) remove the RO properties from the plant-ontology.obo file and (2) import the ro_import.obo file ? Thanks

**Comment by cmungall** [comment]
So long as we're not editing in OE any more, we should just manually 
delete the relation stanzas in the plant-ontology.obo file and rely on 
the import file

I would do this in a text editor. All Typedefs will be in one chunk.

(I am offline and have not looked at your PR, so not sure if you are 
doing this already)

**Comment by marieALaporte** [comment]
@cooperl09 the PR can be accepted and then the plant-ontology.obo file must be edited as mentioned in Chris' comment.

**Pull request merged**
